# See catalan.conf.
#
# This is the configuration for the Arabic keyboard.
[ids]
0001:0001

# Include the layout "ara": Arabic.
include layouts/ara

# Any adjustments you may want to make to layout "ara" to match your keyboard go here ...

# I still want keyboard shortcuts for common menu items, like Ctrl+C for "Copy".
# I still want to use the same key, even though that key is now ؤ not C. (It has C and ؤ printed on it.)
# So this maps physical keys back to Latin letters when Control is held.
[ara+control]
a = C-a
b = C-b
c = C-c
d = C-d
e = C-e
f = C-f
g = C-g
h = C-h
i = C-i
j = C-j
k = C-k
l = C-l
m = C-m
n = C-n
o = C-o
p = C-p
q = C-q
r = C-r
s = C-s
t = C-t
u = C-u
v = C-v
w = C-w
x = C-x
y = C-y
z = C-z

# For this identified keyboard, use the layout "ara".
[global]
default_layout = ara