# Aim: connect two physical keyboards with different layouts to the computer at the same time,
# for example a Catalan and an Arabic keyboard.
# The user can type on both keyboards without having to switch layout in the OS UI.
# The OS must use "English (US, intl, with dead keys)", with dead keys.
#
# The example here is:
# "Apple, Inc Apple Keyboard" with identifier "05ac:0221" and layout "Catalan (Spain, with middle-dot L)" and
# "AT Translated Set 2 keyboard" with identifier "0001:0001" and layout "Arabic (Syria)".
# My OS is Ubuntu 25.10.
#
# In Ubuntu 25.10, you must choose "English (US, intl, with dead keys)".
# (It doesn't matter whether there are others in list as long as they are not selected.)
#
#
# This is the configuration for the Catalan keyboard.
[ids]
05ac:0221

# Include the layout "es": Spanish (which is the Catalan variant).
include layouts/es

# Any adjustments you may want to make to layout "es" to match your keyboard go here ...

# For this identified keyboard, use the layout "es".
[global]
default_layout = es